// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: office/office.proto

package office

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Office_GetUserTags_FullMethodName               = "/OpenIMChat.office.Office/GetUserTags"
	Office_CreateTag_FullMethodName                 = "/OpenIMChat.office.Office/CreateTag"
	Office_DeleteTag_FullMethodName                 = "/OpenIMChat.office.Office/DeleteTag"
	Office_SetTag_FullMethodName                    = "/OpenIMChat.office.Office/SetTag"
	Office_SendMsg2Tag_FullMethodName               = "/OpenIMChat.office.Office/SendMsg2Tag"
	Office_GetTagSendLogs_FullMethodName            = "/OpenIMChat.office.Office/GetTagSendLogs"
	Office_DelTagSendLog_FullMethodName             = "/OpenIMChat.office.Office/DelTagSendLog"
	Office_GetUserTagByID_FullMethodName            = "/OpenIMChat.office.Office/GetUserTagByID"
	Office_CreateOneWorkMoment_FullMethodName       = "/OpenIMChat.office.Office/CreateOneWorkMoment"
	Office_DeleteOneWorkMoment_FullMethodName       = "/OpenIMChat.office.Office/DeleteOneWorkMoment"
	Office_LikeOneWorkMoment_FullMethodName         = "/OpenIMChat.office.Office/LikeOneWorkMoment"
	Office_CommentOneWorkMoment_FullMethodName      = "/OpenIMChat.office.Office/CommentOneWorkMoment"
	Office_DeleteComment_FullMethodName             = "/OpenIMChat.office.Office/DeleteComment"
	Office_GetWorkMomentByID_FullMethodName         = "/OpenIMChat.office.Office/GetWorkMomentByID"
	Office_GetUserSendWorkMoments_FullMethodName    = "/OpenIMChat.office.Office/GetUserSendWorkMoments"
	Office_GetUserRecvWorkMoments_FullMethodName    = "/OpenIMChat.office.Office/GetUserRecvWorkMoments"
	Office_FindRelevantWorkMoments_FullMethodName   = "/OpenIMChat.office.Office/FindRelevantWorkMoments"
	Office_GetUnreadWorkMomentsCount_FullMethodName = "/OpenIMChat.office.Office/GetUnreadWorkMomentsCount"
	Office_ReadWorkMoments_FullMethodName           = "/OpenIMChat.office.Office/ReadWorkMoments"
)

// OfficeClient is the client API for Office service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OfficeClient interface {
	GetUserTags(ctx context.Context, in *GetUserTagsReq, opts ...grpc.CallOption) (*GetUserTagsResp, error)
	CreateTag(ctx context.Context, in *CreateTagReq, opts ...grpc.CallOption) (*CreateTagResp, error)
	DeleteTag(ctx context.Context, in *DeleteTagReq, opts ...grpc.CallOption) (*DeleteTagResp, error)
	SetTag(ctx context.Context, in *SetTagReq, opts ...grpc.CallOption) (*SetTagResp, error)
	SendMsg2Tag(ctx context.Context, in *SendMsg2TagReq, opts ...grpc.CallOption) (*SendMsg2TagResp, error)
	GetTagSendLogs(ctx context.Context, in *GetTagSendLogsReq, opts ...grpc.CallOption) (*GetTagSendLogsResp, error)
	DelTagSendLog(ctx context.Context, in *DelTagSendLogReq, opts ...grpc.CallOption) (*DelTagSendLogResp, error)
	GetUserTagByID(ctx context.Context, in *GetUserTagByIDReq, opts ...grpc.CallOption) (*GetUserTagByIDResp, error)
	CreateOneWorkMoment(ctx context.Context, in *CreateOneWorkMomentReq, opts ...grpc.CallOption) (*CreateOneWorkMomentResp, error)
	DeleteOneWorkMoment(ctx context.Context, in *DeleteOneWorkMomentReq, opts ...grpc.CallOption) (*DeleteOneWorkMomentResp, error)
	LikeOneWorkMoment(ctx context.Context, in *LikeOneWorkMomentReq, opts ...grpc.CallOption) (*LikeOneWorkMomentResp, error)
	CommentOneWorkMoment(ctx context.Context, in *CommentOneWorkMomentReq, opts ...grpc.CallOption) (*CommentOneWorkMomentResp, error)
	DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
	GetWorkMomentByID(ctx context.Context, in *GetWorkMomentByIDReq, opts ...grpc.CallOption) (*GetWorkMomentByIDResp, error)
	GetUserSendWorkMoments(ctx context.Context, in *GetUserSendWorkMomentsReq, opts ...grpc.CallOption) (*GetUserSendWorkMomentsResp, error)
	GetUserRecvWorkMoments(ctx context.Context, in *GetUserRecvWorkMomentsReq, opts ...grpc.CallOption) (*GetUserRecvWorkMomentsResp, error)
	FindRelevantWorkMoments(ctx context.Context, in *FindRelevantWorkMomentsReq, opts ...grpc.CallOption) (*FindRelevantWorkMomentsResp, error)
	GetUnreadWorkMomentsCount(ctx context.Context, in *GetUnreadWorkMomentsCountReq, opts ...grpc.CallOption) (*GetUnreadWorkMomentsCountResp, error)
	ReadWorkMoments(ctx context.Context, in *ReadWorkMomentsReq, opts ...grpc.CallOption) (*ReadWorkMomentsResp, error)
}

type officeClient struct {
	cc grpc.ClientConnInterface
}

func NewOfficeClient(cc grpc.ClientConnInterface) OfficeClient {
	return &officeClient{cc}
}

func (c *officeClient) GetUserTags(ctx context.Context, in *GetUserTagsReq, opts ...grpc.CallOption) (*GetUserTagsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTagsResp)
	err := c.cc.Invoke(ctx, Office_GetUserTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) CreateTag(ctx context.Context, in *CreateTagReq, opts ...grpc.CallOption) (*CreateTagResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTagResp)
	err := c.cc.Invoke(ctx, Office_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) DeleteTag(ctx context.Context, in *DeleteTagReq, opts ...grpc.CallOption) (*DeleteTagResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTagResp)
	err := c.cc.Invoke(ctx, Office_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) SetTag(ctx context.Context, in *SetTagReq, opts ...grpc.CallOption) (*SetTagResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTagResp)
	err := c.cc.Invoke(ctx, Office_SetTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) SendMsg2Tag(ctx context.Context, in *SendMsg2TagReq, opts ...grpc.CallOption) (*SendMsg2TagResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMsg2TagResp)
	err := c.cc.Invoke(ctx, Office_SendMsg2Tag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) GetTagSendLogs(ctx context.Context, in *GetTagSendLogsReq, opts ...grpc.CallOption) (*GetTagSendLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTagSendLogsResp)
	err := c.cc.Invoke(ctx, Office_GetTagSendLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) DelTagSendLog(ctx context.Context, in *DelTagSendLogReq, opts ...grpc.CallOption) (*DelTagSendLogResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelTagSendLogResp)
	err := c.cc.Invoke(ctx, Office_DelTagSendLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) GetUserTagByID(ctx context.Context, in *GetUserTagByIDReq, opts ...grpc.CallOption) (*GetUserTagByIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTagByIDResp)
	err := c.cc.Invoke(ctx, Office_GetUserTagByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) CreateOneWorkMoment(ctx context.Context, in *CreateOneWorkMomentReq, opts ...grpc.CallOption) (*CreateOneWorkMomentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOneWorkMomentResp)
	err := c.cc.Invoke(ctx, Office_CreateOneWorkMoment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) DeleteOneWorkMoment(ctx context.Context, in *DeleteOneWorkMomentReq, opts ...grpc.CallOption) (*DeleteOneWorkMomentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOneWorkMomentResp)
	err := c.cc.Invoke(ctx, Office_DeleteOneWorkMoment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) LikeOneWorkMoment(ctx context.Context, in *LikeOneWorkMomentReq, opts ...grpc.CallOption) (*LikeOneWorkMomentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeOneWorkMomentResp)
	err := c.cc.Invoke(ctx, Office_LikeOneWorkMoment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) CommentOneWorkMoment(ctx context.Context, in *CommentOneWorkMomentReq, opts ...grpc.CallOption) (*CommentOneWorkMomentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentOneWorkMomentResp)
	err := c.cc.Invoke(ctx, Office_CommentOneWorkMoment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentResp)
	err := c.cc.Invoke(ctx, Office_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) GetWorkMomentByID(ctx context.Context, in *GetWorkMomentByIDReq, opts ...grpc.CallOption) (*GetWorkMomentByIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkMomentByIDResp)
	err := c.cc.Invoke(ctx, Office_GetWorkMomentByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) GetUserSendWorkMoments(ctx context.Context, in *GetUserSendWorkMomentsReq, opts ...grpc.CallOption) (*GetUserSendWorkMomentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSendWorkMomentsResp)
	err := c.cc.Invoke(ctx, Office_GetUserSendWorkMoments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) GetUserRecvWorkMoments(ctx context.Context, in *GetUserRecvWorkMomentsReq, opts ...grpc.CallOption) (*GetUserRecvWorkMomentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRecvWorkMomentsResp)
	err := c.cc.Invoke(ctx, Office_GetUserRecvWorkMoments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) FindRelevantWorkMoments(ctx context.Context, in *FindRelevantWorkMomentsReq, opts ...grpc.CallOption) (*FindRelevantWorkMomentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindRelevantWorkMomentsResp)
	err := c.cc.Invoke(ctx, Office_FindRelevantWorkMoments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) GetUnreadWorkMomentsCount(ctx context.Context, in *GetUnreadWorkMomentsCountReq, opts ...grpc.CallOption) (*GetUnreadWorkMomentsCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadWorkMomentsCountResp)
	err := c.cc.Invoke(ctx, Office_GetUnreadWorkMomentsCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeClient) ReadWorkMoments(ctx context.Context, in *ReadWorkMomentsReq, opts ...grpc.CallOption) (*ReadWorkMomentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadWorkMomentsResp)
	err := c.cc.Invoke(ctx, Office_ReadWorkMoments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfficeServer is the server API for Office service.
// All implementations must embed UnimplementedOfficeServer
// for forward compatibility.
type OfficeServer interface {
	GetUserTags(context.Context, *GetUserTagsReq) (*GetUserTagsResp, error)
	CreateTag(context.Context, *CreateTagReq) (*CreateTagResp, error)
	DeleteTag(context.Context, *DeleteTagReq) (*DeleteTagResp, error)
	SetTag(context.Context, *SetTagReq) (*SetTagResp, error)
	SendMsg2Tag(context.Context, *SendMsg2TagReq) (*SendMsg2TagResp, error)
	GetTagSendLogs(context.Context, *GetTagSendLogsReq) (*GetTagSendLogsResp, error)
	DelTagSendLog(context.Context, *DelTagSendLogReq) (*DelTagSendLogResp, error)
	GetUserTagByID(context.Context, *GetUserTagByIDReq) (*GetUserTagByIDResp, error)
	CreateOneWorkMoment(context.Context, *CreateOneWorkMomentReq) (*CreateOneWorkMomentResp, error)
	DeleteOneWorkMoment(context.Context, *DeleteOneWorkMomentReq) (*DeleteOneWorkMomentResp, error)
	LikeOneWorkMoment(context.Context, *LikeOneWorkMomentReq) (*LikeOneWorkMomentResp, error)
	CommentOneWorkMoment(context.Context, *CommentOneWorkMomentReq) (*CommentOneWorkMomentResp, error)
	DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error)
	GetWorkMomentByID(context.Context, *GetWorkMomentByIDReq) (*GetWorkMomentByIDResp, error)
	GetUserSendWorkMoments(context.Context, *GetUserSendWorkMomentsReq) (*GetUserSendWorkMomentsResp, error)
	GetUserRecvWorkMoments(context.Context, *GetUserRecvWorkMomentsReq) (*GetUserRecvWorkMomentsResp, error)
	FindRelevantWorkMoments(context.Context, *FindRelevantWorkMomentsReq) (*FindRelevantWorkMomentsResp, error)
	GetUnreadWorkMomentsCount(context.Context, *GetUnreadWorkMomentsCountReq) (*GetUnreadWorkMomentsCountResp, error)
	ReadWorkMoments(context.Context, *ReadWorkMomentsReq) (*ReadWorkMomentsResp, error)
	mustEmbedUnimplementedOfficeServer()
}

// UnimplementedOfficeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOfficeServer struct{}

func (UnimplementedOfficeServer) GetUserTags(context.Context, *GetUserTagsReq) (*GetUserTagsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTags not implemented")
}
func (UnimplementedOfficeServer) CreateTag(context.Context, *CreateTagReq) (*CreateTagResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedOfficeServer) DeleteTag(context.Context, *DeleteTagReq) (*DeleteTagResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedOfficeServer) SetTag(context.Context, *SetTagReq) (*SetTagResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTag not implemented")
}
func (UnimplementedOfficeServer) SendMsg2Tag(context.Context, *SendMsg2TagReq) (*SendMsg2TagResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMsg2Tag not implemented")
}
func (UnimplementedOfficeServer) GetTagSendLogs(context.Context, *GetTagSendLogsReq) (*GetTagSendLogsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTagSendLogs not implemented")
}
func (UnimplementedOfficeServer) DelTagSendLog(context.Context, *DelTagSendLogReq) (*DelTagSendLogResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DelTagSendLog not implemented")
}
func (UnimplementedOfficeServer) GetUserTagByID(context.Context, *GetUserTagByIDReq) (*GetUserTagByIDResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTagByID not implemented")
}
func (UnimplementedOfficeServer) CreateOneWorkMoment(context.Context, *CreateOneWorkMomentReq) (*CreateOneWorkMomentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOneWorkMoment not implemented")
}
func (UnimplementedOfficeServer) DeleteOneWorkMoment(context.Context, *DeleteOneWorkMomentReq) (*DeleteOneWorkMomentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOneWorkMoment not implemented")
}
func (UnimplementedOfficeServer) LikeOneWorkMoment(context.Context, *LikeOneWorkMomentReq) (*LikeOneWorkMomentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeOneWorkMoment not implemented")
}
func (UnimplementedOfficeServer) CommentOneWorkMoment(context.Context, *CommentOneWorkMomentReq) (*CommentOneWorkMomentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CommentOneWorkMoment not implemented")
}
func (UnimplementedOfficeServer) DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedOfficeServer) GetWorkMomentByID(context.Context, *GetWorkMomentByIDReq) (*GetWorkMomentByIDResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkMomentByID not implemented")
}
func (UnimplementedOfficeServer) GetUserSendWorkMoments(context.Context, *GetUserSendWorkMomentsReq) (*GetUserSendWorkMomentsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSendWorkMoments not implemented")
}
func (UnimplementedOfficeServer) GetUserRecvWorkMoments(context.Context, *GetUserRecvWorkMomentsReq) (*GetUserRecvWorkMomentsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRecvWorkMoments not implemented")
}
func (UnimplementedOfficeServer) FindRelevantWorkMoments(context.Context, *FindRelevantWorkMomentsReq) (*FindRelevantWorkMomentsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindRelevantWorkMoments not implemented")
}
func (UnimplementedOfficeServer) GetUnreadWorkMomentsCount(context.Context, *GetUnreadWorkMomentsCountReq) (*GetUnreadWorkMomentsCountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadWorkMomentsCount not implemented")
}
func (UnimplementedOfficeServer) ReadWorkMoments(context.Context, *ReadWorkMomentsReq) (*ReadWorkMomentsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadWorkMoments not implemented")
}
func (UnimplementedOfficeServer) mustEmbedUnimplementedOfficeServer() {}
func (UnimplementedOfficeServer) testEmbeddedByValue()                {}

// UnsafeOfficeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OfficeServer will
// result in compilation errors.
type UnsafeOfficeServer interface {
	mustEmbedUnimplementedOfficeServer()
}

func RegisterOfficeServer(s grpc.ServiceRegistrar, srv OfficeServer) {
	// If the following call panics, it indicates UnimplementedOfficeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Office_ServiceDesc, srv)
}

func _Office_GetUserTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTagsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).GetUserTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_GetUserTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).GetUserTags(ctx, req.(*GetUserTagsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).CreateTag(ctx, req.(*CreateTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).DeleteTag(ctx, req.(*DeleteTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_SetTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).SetTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_SetTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).SetTag(ctx, req.(*SetTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_SendMsg2Tag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMsg2TagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).SendMsg2Tag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_SendMsg2Tag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).SendMsg2Tag(ctx, req.(*SendMsg2TagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_GetTagSendLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagSendLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).GetTagSendLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_GetTagSendLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).GetTagSendLogs(ctx, req.(*GetTagSendLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_DelTagSendLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelTagSendLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).DelTagSendLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_DelTagSendLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).DelTagSendLog(ctx, req.(*DelTagSendLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_GetUserTagByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTagByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).GetUserTagByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_GetUserTagByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).GetUserTagByID(ctx, req.(*GetUserTagByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_CreateOneWorkMoment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOneWorkMomentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).CreateOneWorkMoment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_CreateOneWorkMoment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).CreateOneWorkMoment(ctx, req.(*CreateOneWorkMomentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_DeleteOneWorkMoment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOneWorkMomentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).DeleteOneWorkMoment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_DeleteOneWorkMoment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).DeleteOneWorkMoment(ctx, req.(*DeleteOneWorkMomentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_LikeOneWorkMoment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeOneWorkMomentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).LikeOneWorkMoment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_LikeOneWorkMoment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).LikeOneWorkMoment(ctx, req.(*LikeOneWorkMomentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_CommentOneWorkMoment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentOneWorkMomentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).CommentOneWorkMoment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_CommentOneWorkMoment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).CommentOneWorkMoment(ctx, req.(*CommentOneWorkMomentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).DeleteComment(ctx, req.(*DeleteCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_GetWorkMomentByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkMomentByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).GetWorkMomentByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_GetWorkMomentByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).GetWorkMomentByID(ctx, req.(*GetWorkMomentByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_GetUserSendWorkMoments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSendWorkMomentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).GetUserSendWorkMoments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_GetUserSendWorkMoments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).GetUserSendWorkMoments(ctx, req.(*GetUserSendWorkMomentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_GetUserRecvWorkMoments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRecvWorkMomentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).GetUserRecvWorkMoments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_GetUserRecvWorkMoments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).GetUserRecvWorkMoments(ctx, req.(*GetUserRecvWorkMomentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_FindRelevantWorkMoments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRelevantWorkMomentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).FindRelevantWorkMoments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_FindRelevantWorkMoments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).FindRelevantWorkMoments(ctx, req.(*FindRelevantWorkMomentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_GetUnreadWorkMomentsCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadWorkMomentsCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).GetUnreadWorkMomentsCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_GetUnreadWorkMomentsCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).GetUnreadWorkMomentsCount(ctx, req.(*GetUnreadWorkMomentsCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Office_ReadWorkMoments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadWorkMomentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServer).ReadWorkMoments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Office_ReadWorkMoments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServer).ReadWorkMoments(ctx, req.(*ReadWorkMomentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Office_ServiceDesc is the grpc.ServiceDesc for Office service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Office_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OpenIMChat.office.Office",
	HandlerType: (*OfficeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserTags",
			Handler:    _Office_GetUserTags_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _Office_CreateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _Office_DeleteTag_Handler,
		},
		{
			MethodName: "SetTag",
			Handler:    _Office_SetTag_Handler,
		},
		{
			MethodName: "SendMsg2Tag",
			Handler:    _Office_SendMsg2Tag_Handler,
		},
		{
			MethodName: "GetTagSendLogs",
			Handler:    _Office_GetTagSendLogs_Handler,
		},
		{
			MethodName: "DelTagSendLog",
			Handler:    _Office_DelTagSendLog_Handler,
		},
		{
			MethodName: "GetUserTagByID",
			Handler:    _Office_GetUserTagByID_Handler,
		},
		{
			MethodName: "CreateOneWorkMoment",
			Handler:    _Office_CreateOneWorkMoment_Handler,
		},
		{
			MethodName: "DeleteOneWorkMoment",
			Handler:    _Office_DeleteOneWorkMoment_Handler,
		},
		{
			MethodName: "LikeOneWorkMoment",
			Handler:    _Office_LikeOneWorkMoment_Handler,
		},
		{
			MethodName: "CommentOneWorkMoment",
			Handler:    _Office_CommentOneWorkMoment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _Office_DeleteComment_Handler,
		},
		{
			MethodName: "GetWorkMomentByID",
			Handler:    _Office_GetWorkMomentByID_Handler,
		},
		{
			MethodName: "GetUserSendWorkMoments",
			Handler:    _Office_GetUserSendWorkMoments_Handler,
		},
		{
			MethodName: "GetUserRecvWorkMoments",
			Handler:    _Office_GetUserRecvWorkMoments_Handler,
		},
		{
			MethodName: "FindRelevantWorkMoments",
			Handler:    _Office_FindRelevantWorkMoments_Handler,
		},
		{
			MethodName: "GetUnreadWorkMomentsCount",
			Handler:    _Office_GetUnreadWorkMomentsCount_Handler,
		},
		{
			MethodName: "ReadWorkMoments",
			Handler:    _Office_ReadWorkMoments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "office/office.proto",
}
